import React, { useCallback, useState } from "react";
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useFocusEffect } from "@react-navigation/native";

import { createHistory, getHistory } from "../services/api";

export default function HistoryScreen({ navigation }) {
  const [items, setItems] = useState([]);
  const [form, setForm] = useState({ paciente: "Maria Silva", cuidador: "Ana Cuidadora", data_atendimento: new Date().toISOString().slice(0,10), horario_inicio: "09:00", horario_fim: "12:00", procedimentos: "Acompanhamento domiciliar e relatório ao familiar.", observacoes: "Atendimento registrado pelo app." });
  const [showForm, setShowForm] = useState(false);
  const load = useCallback(async () => { try { setItems(await getHistory()); } catch (e) { Alert.alert("Erro", e.message); } }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  function update(k,v){ setForm(o => ({...o,[k]:v})); }
  async function save(){ try { await createHistory(form); setShowForm(false); load(); Alert.alert("Sucesso", "Histórico registrado."); } catch(e){ Alert.alert("Erro", e.message); } }

  return <SafeAreaView style={styles.screen}><ScrollView contentContainerStyle={styles.container}><Back navigation={navigation}/><Text style={styles.title}>Histórico de atendimento</Text><TouchableOpacity style={styles.buttonOutline} onPress={()=>setShowForm(!showForm)}><Text style={styles.buttonOutlineText}>{showForm ? "Ocultar formulário" : "+ Registrar atendimento"}</Text></TouchableOpacity>{showForm && <View style={styles.form}><Input label="Paciente" value={form.paciente} onChangeText={(v)=>update('paciente',v)}/><Input label="Cuidador" value={form.cuidador} onChangeText={(v)=>update('cuidador',v)}/><Input label="Data" value={form.data_atendimento} onChangeText={(v)=>update('data_atendimento',v)}/><Input label="Início" value={form.horario_inicio} onChangeText={(v)=>update('horario_inicio',v)}/><Input label="Fim" value={form.horario_fim} onChangeText={(v)=>update('horario_fim',v)}/><Input label="Procedimentos" value={form.procedimentos} onChangeText={(v)=>update('procedimentos',v)} multiline/><Input label="Observações" value={form.observacoes} onChangeText={(v)=>update('observacoes',v)} multiline/><Button title="Salvar histórico" onPress={save}/></View>}{items.map((item)=><View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.paciente}</Text><Text>Cuidador: {item.cuidador}</Text><Text>Data: {formatDate(item.data_atendimento)}</Text><Text>Horário: {String(item.horario_inicio || '').slice(0,5)} - {String(item.horario_fim || '').slice(0,5)}</Text><Text style={styles.bold}>Procedimentos:</Text><Text>{item.procedimentos}</Text><Text style={styles.status}>{item.status}</Text></View>)}</ScrollView></SafeAreaView>;
}
function formatDate(v){ return v ? String(v).slice(0,10).split('-').reverse().join('/') : ''; }
function Input(props){return <View style={styles.field}><Text style={styles.label}>{props.label}</Text><TextInput style={[styles.input,props.multiline&&styles.textArea]} {...props}/></View>}
function Button({title,onPress}){return <TouchableOpacity style={styles.button} onPress={onPress}><Text style={styles.buttonText}>{title}</Text></TouchableOpacity>}
function Back({navigation}){return <TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Text style={styles.backText}>← Voltar</Text></TouchableOpacity>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#EAF6FF", padding:10},container:{padding:20,paddingBottom:40},back:{alignSelf:"flex-start",marginBottom:12},backText:{color:"#2563EB",fontWeight:"bold"},title:{fontSize:28,fontWeight:"bold",color:"#0F2A44",marginBottom:12},buttonOutline:{backgroundColor:"#fff",borderColor:"#2563EB",borderWidth:1,borderRadius:14,padding:14,marginBottom:14},buttonOutlineText:{color:"#2563EB",textAlign:"center",fontWeight:"bold"},form:{backgroundColor:"#fff",borderRadius:18,padding:16,marginBottom:16},field:{marginBottom:10},label:{fontWeight:"bold",marginBottom:4,color:"#0F2A44"},input:{backgroundColor:"#F8FBFF",borderRadius:12,borderWidth:1,borderColor:"#CFE3FF",padding:12},textArea:{minHeight:80,textAlignVertical:"top"},button:{backgroundColor:"#2563EB",borderRadius:14,padding:14,alignItems:"center"},buttonText:{color:"#fff",fontWeight:"bold"},card:{backgroundColor:"#fff",borderRadius:18,padding:16,marginBottom:14},cardTitle:{fontSize:18,fontWeight:"bold",color:"#0F2A44"},bold:{fontWeight:"bold",marginTop:8},status:{color:"#16A34A",fontWeight:"bold",marginTop:8}});
